class BeerFields:
    fields = [
        'id',
        'name',
        'description',
        'abv',
        'ibu',
        'glasswareId',
        'glass',
        'styleId',
        'style',
        'isOrganic',
        'foodPairings',
        'originalGravity',
        'labels',
        'servingTemperature',
        'servingTemperatureDisplay',
        'status',
        'statusDisplay',
        'availableId',
        'available',
        'beerVariationId',
        'beerVariation',
        'year',
        'createDate',
        'updateDate'
    ]